name: sbdd
channels:
  - conda-forge
  - defaults
dependencies:
  # Chemistry & molecular modelling
  - rdkit
  - openbabel
  - biopython
  - pdbfixer
  - openmm
  - openmmforcefields
  - openff-toolkit
  - ambertools
  - oddt
  - pdb2pqr

  # Data / numerics / plotting
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn

  # CLI utilities
  - tqdm

  # pip-only packages
  - pip
  - pip:
    - rich-argparse
    - argcomplete
